dist: xenial
language: java
sudo: false
jdk: openjdk11
install: true
addons:
  sonarcloud:
    organization: deivy-spaulonci
    token: f8af0653d99ea0edb614d7247c014273ce83bdbc
script: - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=deivy-spaulonci_VxAssist
cache:
  directories:
    - $HOME/.m2
    - $home/.sonar/cache
