dist: xenial
language: java
sudo: false
jdk: openjdk11
install: true
addons:
  sonarcloud:
    organization: $SONAR_ORGANIZATION
    token: $SONAR_TOKEN
script: - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=deivy-spaulonci_VxAssist
cache:
  directories:
    - $HOME/.m2
    - $home/.sonar/cache
